/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import models.Customer;
import services.CustomerService;
import services.SessionManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author xuanb
 */
public class GUI_Login extends javax.swing.JFrame {

    private CustomerService customerService;

    /**
     * Creates new form GUI_Login
     */
    public GUI_Login() {
        this.customerService = new CustomerService();
        initComponents();
        setupUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        cboRole = new javax.swing.JComboBox<>();
        txtPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ĐĂNG NHẬP");

        jLabel2.setText("Tài khoản");

        jLabel3.setText("Mật khẩu");

        btnLogin.setText("Đăng nhập");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        cboRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CUSTOMER", "EMPLOYEE", "ADMIN" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cboRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                .addComponent(txtPassword))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(cboRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        handleLogin();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void setupUI() {
        // Enter key để đăng nhập
        txtPassword.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    handleLogin();
                }
            }
        });

        // Focus vào username khi mở
        txtUsername.requestFocus();

        // Tạo PlaceholderText (optional)
        txtUsername.setToolTipText("Nhập tên đăng nhập của bạn");
        txtPassword.setToolTipText("Nhập mật khẩu của bạn");
    }

private void handleLogin() {
        String username = txtUsername.getText().trim();
        String password = new String(txtPassword.getPassword());
        String selectedRole = cboRole.getSelectedItem().toString();

        // Validation
        if (username.isEmpty()) {
            showError("Vui lòng nhập tên đăng nhập!");
            txtUsername.requestFocus();
            return;
        }

        if (password.isEmpty()) {
            showError("Vui lòng nhập mật khẩu!");
            txtPassword.requestFocus();
            return;
        }

        // Hiển thị loading
        btnLogin.setEnabled(false);
        btnLogin.setText("Đang đăng nhập...");


        SwingWorker<Customer, Void> worker = new SwingWorker<Customer, Void>() {
            @Override
            protected Customer doInBackground() throws Exception {

                Customer customer = customerService.login(username, password);
                

                if (customer != null && !"Tất cả".equals(selectedRole)) {
                    if (!selectedRole.equalsIgnoreCase(customer.getAccountType())) {
                        return null; // Role không khớp
                    }
                }
                
                return customer;
            }

            @Override
            protected void done() {
                try {
                    // ✅ ĐỔI: Account → Customer
                    Customer customer = get();

                    if (customer != null) {
                        // Đăng nhập thành công
                        onLoginSuccess(customer);
                    } else {
                        // Đăng nhập thất bại
                        showError("Tên đăng nhập, mật khẩu hoặc vai trò không đúng!");
                        txtPassword.setText("");
                        txtPassword.requestFocus();
                    }

                } catch (Exception e) {
                    showError("Lỗi khi đăng nhập: " + e.getMessage());
                    e.printStackTrace();
                } finally {
                    btnLogin.setEnabled(true);
                    btnLogin.setText("ĐĂNG NHẬP");
                }
            }
        };

        worker.execute();
    }

    /**
     * Xử lý khi đăng nhập thành công
     */
    private void onLoginSuccess(Customer customer) {
        // ✅ ĐỔI: setCurrentAccount → setCurrentCustomer
        SessionManager.getInstance().setCurrentCustomer(customer);

        // Hiển thị thông báo
        JOptionPane.showMessageDialog(this,
                "Đăng nhập thành công!\n\n"
                + "Xin chào: " + customer.getFullName() + "\n"
                + "Vai trò: " + customer.getAccountType(),
                "Thành công",
                JOptionPane.INFORMATION_MESSAGE
        );

        // ✅ ĐỔI: Dùng helper methods
        SwingUtilities.invokeLater(() -> {
            if (customer.isAdmin()) {
                // Mở GUI Admin
                GUI_mainAD mainAD = new GUI_mainAD();
                mainAD.setVisible(true);
            } else if (customer.isEmployee()) {
                // Mở GUI Employee (hoặc dùng chung GUI_mainkh)
                GUI_mainkh mainGUI = new GUI_mainkh();
                mainGUI.setVisible(true);
            } else if (customer.isCustomer()) {
                // Mở GUI Customer
                GUI_mainkh mainGUI = new GUI_mainkh();
                mainGUI.setVisible(true);
            } else {
                showError("Vai trò không xác định!");
                return;
            }
            
            this.dispose();
        });
    }

    /**
     * Hiển thị lỗi
     */
    private void showError(String message) {
        JOptionPane.showMessageDialog(this,
                message,
                "Lỗi đăng nhập",
                JOptionPane.ERROR_MESSAGE
        );
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> cboRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
