/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import services.SessionManager;
import javax.swing.JOptionPane;
import java.awt.CardLayout;
import javax.swing.JPanel;
/**
 *
 * @author xuanb
 */
public class GUI_mainAD extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUI_mainAD.class.getName());
    private CardLayout cardLayout;

    /**
     * Creates new form GUI_main
     */
    public GUI_mainAD() {
        initComponents();
        cardLayout = new CardLayout();
        pnlMain.setLayout(cardLayout);

        // Xóa component cũ
        pnlMain.removeAll();

        // Thêm các panel
        pnlMain.add(new JPanel_qltour(), "QuanlyTour");
        pnlMain.add(new JPanel_qlks(), "QLKS");
//        pnlMain.add(new JPanel_qltaikhoan(), "QLTK");
        pnlMain.add(new JPanel_qlxe(), "QLXe");
        pnlMain.add(new JPanel_thongke(), "Thongke");        
        pnlMain.add(new JPanel_Dattourkh(), "DatTour");
                pnlMain.add(new JPanel_qltaikhoan(), "QLTaiKhoan");



        // Hiển thị panel đầu tiên
        cardLayout.show(pnlMain, "DatTour");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnQLKS = new javax.swing.JButton();
        btnQLT = new javax.swing.JButton();
        btnQLX = new javax.swing.JButton();
        btnQLTK = new javax.swing.JButton();
        btnTK = new javax.swing.JButton();
        btnDattour = new javax.swing.JButton();
        pnlMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("QUẢN LÝ TOUR DU LỊCH");

        jButton1.setText("Đăng xuất");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnQLKS.setText("Quản lý khách sạn");
        btnQLKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLKSActionPerformed(evt);
            }
        });

        btnQLT.setText("Quản lý tour");
        btnQLT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLTActionPerformed(evt);
            }
        });

        btnQLX.setText("Quản lý xe");
        btnQLX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLXActionPerformed(evt);
            }
        });

        btnQLTK.setText("Quản lý tài khoản");
        btnQLTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLTKActionPerformed(evt);
            }
        });

        btnTK.setText("Thống kê");
        btnTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKActionPerformed(evt);
            }
        });

        btnDattour.setText("Đặt Tour");
        btnDattour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDattourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(btnDattour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQLT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQLKS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQLX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQLTK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTK)
                .addGap(188, 188, 188))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQLT)
                    .addComponent(btnQLKS)
                    .addComponent(btnQLX)
                    .addComponent(btnQLTK)
                    .addComponent(btnTK)
                    .addComponent(btnDattour))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlMain.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQLTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLTActionPerformed
        // TODO add your handling code here:
        cardLayout.show(pnlMain, "QuanlyTour");
    }//GEN-LAST:event_btnQLTActionPerformed

    private void btnQLKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLKSActionPerformed
        // TODO add your handling code here:
        cardLayout.show(pnlMain, "QLKS");
    }//GEN-LAST:event_btnQLKSActionPerformed

    private void btnQLXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLXActionPerformed
        // TODO add your handling code here:
        cardLayout.show(pnlMain, "QLXe");
    }//GEN-LAST:event_btnQLXActionPerformed

    private void btnQLTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLTKActionPerformed
        // TODO add your handling code here:
        cardLayout.show(pnlMain, "QLTaiKhoan");
    }//GEN-LAST:event_btnQLTKActionPerformed

    private void btnTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKActionPerformed
        // TODO add your handling code here:
        cardLayout.show(pnlMain, "Thongke");
    }//GEN-LAST:event_btnTKActionPerformed

    private void btnDattourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDattourActionPerformed
        // TODO add your handling code here:
                cardLayout.show(pnlMain, "DatTour");

    }//GEN-LAST:event_btnDattourActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(this, 
        "Bạn có chắc muốn đăng xuất?", 
        "Xác nhận đăng xuất", 
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE);
    
    if (choice == JOptionPane.YES_OPTION) {
        // Lưu thông tin user trước khi logout
        String username = SessionManager.getInstance().getCurrentUsername();
        
        // Logout
        SessionManager.getInstance().logout();
        
        // Thông báo
        JOptionPane.showMessageDialog(this, 
            "Đã đăng xuất thành công!\nTạm biệt " + username + "!", 
            "Đăng xuất", 
            JOptionPane.INFORMATION_MESSAGE);
        
        // Đóng GUI hiện tại
        this.dispose();
        
        // Mở lại GUI Login
        java.awt.EventQueue.invokeLater(() -> {
            new GUI_Login().setVisible(true);
        });
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUI_mainAD().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDattour;
    private javax.swing.JButton btnQLKS;
    private javax.swing.JButton btnQLT;
    private javax.swing.JButton btnQLTK;
    private javax.swing.JButton btnQLX;
    private javax.swing.JButton btnTK;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
