/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Date;
import models.Tour;
import models.Vehicle;
import models.Hotel;

import services.RelationshipService;
import services.TourService;
import services.VehicleService;
import services.HotelService;
import java.util.List;
/**
 *
 * @author xuanb
 */
public class JPanel_qltour extends javax.swing.JPanel {
    private TourService tourService;
    private VehicleService vehicleService;
    private HotelService hotelService;
    private DefaultTableModel tableModel;
    private RelationshipService relationshipService;
    /**
     * Creates new form JPanel_qltour
     */
    public JPanel_qltour() {
        this.tourService = new TourService();
        this.vehicleService = new VehicleService();
        this.hotelService = new HotelService();
        this.relationshipService = new RelationshipService();
        initComponents();
        khoiTaoDuLieu();
        this.addComponentListener(new java.awt.event.ComponentAdapter() {
        @Override
        public void componentShown(java.awt.event.ComponentEvent evt) {
            khoiTaoDuLieu();
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSachTour = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimkiem = new javax.swing.JButton();
        txtMaTour = new javax.swing.JTextField();
        txtTenTour = new javax.swing.JTextField();
        txtThoiGian = new javax.swing.JTextField();
        txtDiemDen = new javax.swing.JTextField();
        cboXe = new javax.swing.JComboBox<>();
        cboKhachSan = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtGiaNguoiLon = new javax.swing.JTextField();
        txtGiaTreEm = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSoChoToiDa = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtMoTa = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cboTrangThai = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(800, 310));

        jLabel1.setText("Mã Tour:");

        jLabel2.setText("Tên Tour:");

        jLabel3.setText("Thời gian:");

        jLabel4.setText("Địa điểm:");

        jLabel5.setText("Mã xe:");

        jLabel6.setText("Mã khách sạn:");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        tblDanhSachTour.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Tour", "Tên Tour", "Địa điểm", "Thời gian", "Giá người lớn", "Giá trẻ em", "Số người tối đa", "Trạng thái", "Mã xe", "Mã khách sạn", "Mô tả"
            }
        ));
        jScrollPane1.setViewportView(tblDanhSachTour);

        jLabel7.setText("Tìm kiếm");

        btnTimkiem.setText("Tìm kiếm");
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });

        cboXe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboKhachSan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Giá người lớn");

        txtGiaTreEm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaTreEmActionPerformed(evt);
            }
        });

        jLabel9.setText("Giá trẻ em");

        txtSoChoToiDa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoChoToiDaActionPerformed(evt);
            }
        });

        jLabel10.setText("Số người tối đa");

        txtMoTa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMoTaActionPerformed(evt);
            }
        });

        jLabel11.setText("Mô tả");

        jLabel12.setText("Trạng thái");

        cboTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AVAILABLE", "Tạm ngưng" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel4))
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtGiaTreEm)
                            .addComponent(txtDiemDen)
                            .addComponent(txtMaTour)
                            .addComponent(txtTenTour, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(txtThoiGian)
                            .addComponent(txtGiaNguoiLon))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel11))
                                .addGap(11, 11, 11))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addGap(6, 6, 6))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboXe, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSoChoToiDa, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThem)
                            .addComponent(btnXoa)
                            .addComponent(btnSua))
                        .addGap(76, 76, 76))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMoTa)
                            .addComponent(cboKhachSan, 0, 182, Short.MAX_VALUE)
                            .addComponent(btnTimkiem))
                        .addGap(0, 185, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(btnThem)
                            .addComponent(txtMaTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(btnXoa)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(btnSua))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtDiemDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtSoChoToiDa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTenTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cboKhachSan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtGiaNguoiLon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtGiaTreEm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtMoTa))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimkiem))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed
        // TODO add your handling code here:
        timKiemTour();
    }//GEN-LAST:event_btnTimkiemActionPerformed

    private void txtGiaTreEmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaTreEmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaTreEmActionPerformed

    private void txtSoChoToiDaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoChoToiDaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoChoToiDaActionPerformed

    private void txtMoTaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMoTaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMoTaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        themTour();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        xoaTour();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        suaTour();
    }//GEN-LAST:event_btnSuaActionPerformed
                                                        

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {                                           
        lamMoiForm();
    }                                                                             

    private void btnHienTatCaActionPerformed(java.awt.event.ActionEvent evt) {                                           
        taiDuLieu();
    }                                          

    private void btnGanXeActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        ganXe();
    }                                                

    private void btnGanKhachSanActionPerformed(java.awt.event.ActionEvent evt) {                                               
        ganKhachSan();
    }                                              

    private void khoiTaoDuLieu() {
        taiDanhSachXe();
        taiDanhSachKhachSan();
        taiDuLieu();
        
        tblDanhSachTour.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                dienFormTuBang();
            }
        });
    }
    
    private void taiDanhSachXe() {
        cboXe.removeAllItems();
        cboXe.addItem("-- Chọn xe --");
        
        try {
            List<Vehicle> danhSachXe = vehicleService.getAllVehicles();
            for (Vehicle xe : danhSachXe) {
                cboXe.addItem(xe.getVehicleId() + " - " + xe.getLicensePlate());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void taiDanhSachKhachSan() {
        cboKhachSan.removeAllItems();
        cboKhachSan.addItem("-- Chọn khách sạn --");
        
        try {
            List<Hotel> danhSachKhachSan = hotelService.getAllHotels();
            for (Hotel ks : danhSachKhachSan) {
                cboKhachSan.addItem(ks.getHotelId() + " - " + ks.getHotelName());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void taiDuLieu() {
        DefaultTableModel model = (DefaultTableModel) tblDanhSachTour.getModel();
        model.setRowCount(0);
        
        try {
            List<Tour> danhSachTour = tourService.getAllTours();
            
            for (Tour tour : danhSachTour) {
                model.addRow(new Object[]{
                    tour.getTourId(),
                    tour.getTourName(),
                    tour.getDestination(),
                    tour.getDuration(),
                    String.format("%,.0f", tour.getPriceAdult()),
                    String.format("%,.0f", tour.getPriceChild()),
                    tour.getMaxParticipants(),
                    tour.getStatus(),
                    tour.getVehicleId() != null ? tour.getVehicleId() : "",
                    tour.getHotelId() != null ? tour.getHotelId() : "",
                    tour.getDescription()
                });
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu: " + e.getMessage());
        }
    }
    
    private void themTour() {
    if (!kiemTraForm()) return;
    
    try {
        Tour tour = new Tour();
        tour.setTourId(txtMaTour.getText().trim());
        tour.setTourName(txtTenTour.getText().trim());
        tour.setDestination(txtDiemDen.getText().trim());
        tour.setDuration(txtThoiGian.getText().trim());
        tour.setPriceAdult(Double.parseDouble(txtGiaNguoiLon.getText().trim()));
        tour.setPriceChild(Double.parseDouble(txtGiaTreEm.getText().trim()));
        tour.setMaxParticipants(Integer.parseInt(txtSoChoToiDa.getText().trim()));
        tour.setDescription(txtMoTa.getText().trim());
        tour.setStatus(cboTrangThai.getSelectedItem().toString());
        tour.setCurrentParticipants(0);
        tour.setDepartureDate(new Date());
        tour.setReturnDate(new Date());
        tour.setCreatedAt(new Date());
        
        // ✅ THÊM: Lưu xe được chọn
        if (cboXe.getSelectedIndex() > 0) {
            String luaChonXe = cboXe.getSelectedItem().toString();
            String maXe = luaChonXe.split(" - ")[0];
            tour.setVehicleId(maXe);
        }
        
        // ✅ THÊM: Lưu khách sạn được chọn
        if (cboKhachSan.getSelectedIndex() > 0) {
            String luaChonKS = cboKhachSan.getSelectedItem().toString();
            String maKS = luaChonKS.split(" - ")[0];
            tour.setHotelId(maKS);
        }
        
        if (tourService.addTour(tour) != null) {
            // ✅ THÊM: Tạo Graph Edges
            String maTour = tour.getTourId();
            
            if (tour.getVehicleId() != null) {
                relationshipService.assignVehicleToTour(maTour, tour.getVehicleId());
            }
            
            if (tour.getHotelId() != null) {
                relationshipService.assignHotelToTour(maTour, tour.getHotelId());
            }
            
            JOptionPane.showMessageDialog(this, "Thêm tour thành công!");
            lamMoiForm();
            taiDuLieu();
        } else {
            JOptionPane.showMessageDialog(this, "Mã tour đã tồn tại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Giá tiền và số chỗ phải là số!", "Lỗi", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
}
    
    private void suaTour() {
    if (txtMaTour.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn tour cần sửa!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        return;
    }
    if (!kiemTraForm()) return;
    
    try {
        Tour tour = tourService.findTourById(txtMaTour.getText().trim());
        if (tour == null) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy tour!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        tour.setTourName(txtTenTour.getText().trim());
        tour.setDestination(txtDiemDen.getText().trim());
        tour.setDuration(txtThoiGian.getText().trim());
        tour.setPriceAdult(Double.parseDouble(txtGiaNguoiLon.getText().trim()));
        tour.setPriceChild(Double.parseDouble(txtGiaTreEm.getText().trim()));
        tour.setMaxParticipants(Integer.parseInt(txtSoChoToiDa.getText().trim()));
        tour.setDescription(txtMoTa.getText().trim());
        tour.setStatus(cboTrangThai.getSelectedItem().toString());
        
        // ✅ THÊM: Cập nhật xe
        if (cboXe.getSelectedIndex() > 0) {
            String luaChonXe = cboXe.getSelectedItem().toString();
            String maXe = luaChonXe.split(" - ")[0];
            
            if (!maXe.equals(tour.getVehicleId())) {
                tour.setVehicleId(maXe);
                relationshipService.assignVehicleToTour(tour.getTourId(), maXe);
            }
        } else {
            tour.setVehicleId(null);
        }
        
        // ✅ THÊM: Cập nhật khách sạn
        if (cboKhachSan.getSelectedIndex() > 0) {
            String luaChonKS = cboKhachSan.getSelectedItem().toString();
            String maKS = luaChonKS.split(" - ")[0];
            
            if (!maKS.equals(tour.getHotelId())) {
                tour.setHotelId(maKS);
                relationshipService.assignHotelToTour(tour.getTourId(), maKS);
            }
        } else {
            tour.setHotelId(null);
        }
        
        if (tourService.updateTour(tour.getTourId(), tour)) {
            JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
            lamMoiForm();
            taiDuLieu();
        }
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Giá tiền và số chỗ phải là số!", "Lỗi", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
}
    
    private void xoaTour() {
        if (txtMaTour.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn tour cần xóa!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int xacNhan = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa tour này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (xacNhan == JOptionPane.YES_OPTION) {
            try {
                if (tourService.deleteTour(txtMaTour.getText().trim())) {
                    JOptionPane.showMessageDialog(this, "Xóa thành công!");
                    lamMoiForm();
                    taiDuLieu();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void timKiemTour() {
        String tuKhoa = txtTimKiem.getText().trim();
        if (tuKhoa.isEmpty()) {
            taiDuLieu();
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblDanhSachTour.getModel();
        model.setRowCount(0);
        
        try {
            List<Tour> danhSachTour = tourService.searchTours(tuKhoa);
            for (Tour tour : danhSachTour) {
                model.addRow(new Object[]{
                    tour.getTourId(),
                    tour.getTourName(),
                    tour.getDestination(),
                    tour.getDuration(),
                    String.format("%,.0f", tour.getPriceAdult()),
                    String.format("%,.0f", tour.getPriceChild()),
                    tour.getMaxParticipants(),
                    tour.getStatus(),
                    tour.getVehicleId() != null ? tour.getVehicleId() : "",
                    tour.getHotelId() != null ? tour.getHotelId() : ""
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi tìm kiếm: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void ganXe() {
        String maTour = txtMaTour.getText().trim();
        
        if (maTour.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn tour!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (cboXe.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn xe!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            String luaChon = cboXe.getSelectedItem().toString();
            String maXe = luaChon.split(" - ")[0];
            
            if (relationshipService.assignVehicleToTour(maTour, maXe)) {
                JOptionPane.showMessageDialog(this, "Gán xe thành công!");
                taiDuLieu();
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi gán xe: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void ganKhachSan() {
        String maTour = txtMaTour.getText().trim();
        
        if (maTour.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn tour!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (cboKhachSan.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn khách sạn!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            String luaChon = cboKhachSan.getSelectedItem().toString();
            String maKhachSan = luaChon.split(" - ")[0];
            
            if (relationshipService.assignHotelToTour(maTour, maKhachSan)) {
                JOptionPane.showMessageDialog(this, "Gán khách sạn thành công!");
                taiDuLieu();
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi gán khách sạn: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void dienFormTuBang() {
        int dongDuocChon = tblDanhSachTour.getSelectedRow();
        if (dongDuocChon >= 0) {
            DefaultTableModel model = (DefaultTableModel) tblDanhSachTour.getModel();
            
            txtMaTour.setText(model.getValueAt(dongDuocChon, 0).toString());
            txtTenTour.setText(model.getValueAt(dongDuocChon, 1).toString());
            txtDiemDen.setText(model.getValueAt(dongDuocChon, 2).toString());
            txtThoiGian.setText(model.getValueAt(dongDuocChon, 3).toString());
            
            String giaNguoiLon = model.getValueAt(dongDuocChon, 4).toString().replace(",", "");
            txtGiaNguoiLon.setText(giaNguoiLon);
            
            String giaTreEm = model.getValueAt(dongDuocChon, 5).toString().replace(",", "");
            txtGiaTreEm.setText(giaTreEm);
            
            txtSoChoToiDa.setText(model.getValueAt(dongDuocChon, 6).toString());
            cboTrangThai.setSelectedItem(model.getValueAt(dongDuocChon, 7).toString());
            
            try {
                Tour tour = tourService.findTourById(txtMaTour.getText());
                if (tour != null) {
                    txtMoTa.setText(tour.getDescription() != null ? tour.getDescription() : "");
                    txtMoTa.setText(model.getValueAt(dongDuocChon, 10).toString());
                    if (tour.getVehicleId() != null) {
                        for (int i = 0; i < cboXe.getItemCount(); i++) {
                            if (cboXe.getItemAt(i).startsWith(tour.getVehicleId())) {
                                cboXe.setSelectedIndex(i);
                                break;
                            }
                        }
                    }
                    
                    if (tour.getHotelId() != null) {
                        for (int i = 0; i < cboKhachSan.getItemCount(); i++) {
                            if (cboKhachSan.getItemAt(i).startsWith(tour.getHotelId())) {
                                cboKhachSan.setSelectedIndex(i);
                                break;
                            }
                        }
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
    
    private void lamMoiForm() {
        txtMaTour.setText("");
        txtTenTour.setText("");
        txtDiemDen.setText("");
        txtThoiGian.setText("");
        txtGiaNguoiLon.setText("");
        txtGiaTreEm.setText("");
        txtSoChoToiDa.setText("");
        txtMoTa.setText("");
        cboTrangThai.setSelectedIndex(0);
        cboXe.setSelectedIndex(0);
        cboKhachSan.setSelectedIndex(0);
        txtTimKiem.setText("");
        tblDanhSachTour.clearSelection();
    }
    
    private boolean kiemTraForm() {
        if (txtMaTour.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã tour!");
            return false;
        }
        if (txtTenTour.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên tour!");
            return false;
        }
        if (txtGiaNguoiLon.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập giá tour!");
            return false;
        }
        if (txtSoChoToiDa.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số chỗ!");
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboKhachSan;
    private javax.swing.JComboBox<String> cboTrangThai;
    private javax.swing.JComboBox<String> cboXe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDanhSachTour;
    private javax.swing.JTextField txtDiemDen;
    private javax.swing.JTextField txtGiaNguoiLon;
    private javax.swing.JTextField txtGiaTreEm;
    private javax.swing.JTextField txtMaTour;
    private javax.swing.JTextField txtMoTa;
    private javax.swing.JTextField txtSoChoToiDa;
    private javax.swing.JTextField txtTenTour;
    private javax.swing.JTextField txtThoiGian;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
