/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import models.Hotel;
import services.HotelService;
import java.util.List;
/**
 *
 * @author xuanb
 */
public class JPanel_qlks extends javax.swing.JPanel {

    /**
     * Creates new form JPanel_qlks
     */    
    private HotelService hotelService;
    private DefaultTableModel tableModel;
    
    public JPanel_qlks() {
                hotelService = new HotelService();
        initComponents();
        setupTableModel();
        loadData();
        setupEventListeners();
        this.addComponentListener(new java.awt.event.ComponentAdapter() {
        @Override
        public void componentShown(java.awt.event.ComponentEvent evt) {
            System.out.println("🔄 [Quản lý KS] Panel hiển thị, đang reload...");
            loadData();
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTimKiem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        txtMaks = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtTenks = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDiachi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtTimkiem = new javax.swing.JTextField();
        btnXoa = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtSdt = new javax.swing.JTextField();

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        jLabel1.setText("Mã khách sạn:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã khách sạn", "Tên khách sạn", "Số điện thoại", "Địa điểm"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Tên khách sạn:");

        jLabel7.setText("Tìm kiếm");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel3.setText("Địa điểm");

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel5.setText("Số điện thoại:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMaks, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                    .addComponent(txtTenks))
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTimKiem)
                                .addGap(162, 162, 162)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThem)
                            .addComponent(btnXoa)
                            .addComponent(btnSua))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXoa)
                            .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtMaks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTenks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnSua))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTimKiem))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void setupTableModel() {
        tableModel = (DefaultTableModel) jTable1.getModel();
        tableModel.setRowCount(0);
    }
    
    /**
     * Setup event listeners
     */
    private void setupEventListeners() {
        // Click vào table để điền form
        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                dienFormTuBang();
            }
        });
        
        // Enter để tìm kiếm
        txtTimkiem.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    btnTimkiemActionPerformed(null);
                }
            }
        });
    }
    
    /**
     * Load dữ liệu lên table
     */
    private void loadData() {
        tableModel.setRowCount(0);
        try {
            List<Hotel> hotels = hotelService.getAllHotels();
            
            for (Hotel h : hotels) {
                Object[] row = {
                    h.getHotelId(),
                    h.getHotelName(),
                    h.getPhone(),
                    h.getAddress()
                };
                tableModel.addRow(row);
            }
            
            System.out.println("✅ Đã load " + hotels.size() + " khách sạn");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "❌ Lỗi khi load dữ liệu: " + e.getMessage(), 
                "Lỗi", 
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    
    /**
     * Điền thông tin từ table vào form
     */
    private void dienFormTuBang() {
        int row = jTable1.getSelectedRow();
        if (row >= 0) {
            try {
                txtMaks.setText(jTable1.getValueAt(row, 0).toString());
                txtTenks.setText(jTable1.getValueAt(row, 1).toString());
                txtSdt.setText(jTable1.getValueAt(row, 2).toString());
                txtDiachi.setText(jTable1.getValueAt(row, 3).toString());
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    
    /**
     * Tìm kiếm khách sạn
     */
    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            String keyword = txtTimkiem.getText().trim();
            
            if (keyword.isEmpty()) {
                loadData();
                return;
            }
            
            tableModel.setRowCount(0);
            List<Hotel> allHotels = hotelService.getAllHotels();
            int count = 0;
            
            for (Hotel h : allHotels) {
                if (h.getHotelId().toLowerCase().contains(keyword.toLowerCase()) ||
                    h.getHotelName().toLowerCase().contains(keyword.toLowerCase()) ||
                    h.getPhone().contains(keyword) ||
                    h.getAddress().toLowerCase().contains(keyword.toLowerCase())) {
                    
                    Object[] row = {
                        h.getHotelId(),
                        h.getHotelName(),
                        h.getPhone(),
                        h.getAddress()
                    };
                    tableModel.addRow(row);
                    count++;
                }
            }
            
            if (count == 0) {
                JOptionPane.showMessageDialog(this, 
                    "❌ Không tìm thấy khách sạn với từ khóa: " + keyword, 
                    "Kết quả", 
                    JOptionPane.INFORMATION_MESSAGE);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "❌ Lỗi: " + e.getMessage(), 
                "Lỗi", 
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    
    /**
     * Làm mới form
     */
    private void btnLammoiActionPerformed(java.awt.event.ActionEvent evt) {
        clearForm();
        loadData();
    }
    
    /**
     * Kiểm tra form
     */
    private boolean kiemTraForm() {
        if (txtMaks.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "⚠️ Vui lòng nhập mã khách sạn!");
            txtMaks.requestFocus();
            return false;
        }
        
        if (txtTenks.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "⚠️ Vui lòng nhập tên khách sạn!");
            txtTenks.requestFocus();
            return false;
        }
        
        if (txtSdt.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "⚠️ Vui lòng nhập số điện thoại!");
            txtSdt.requestFocus();
            return false;
        }
        
        if (txtDiachi.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "⚠️ Vui lòng nhập địa chỉ!");
            txtDiachi.requestFocus();
            return false;
        }
        
        return true;
    }
    
    /**
     * Clear form
     */
    private void clearForm() {
        txtMaks.setText("");
        txtTenks.setText("");
        txtSdt.setText("");
        txtDiachi.setText("");
        txtTimkiem.setText("");
        jTable1.clearSelection();
        txtMaks.requestFocus();
    }   
    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        try {
            String maks = txtMaks.getText().trim();
            
            if (maks.isEmpty()) {
                JOptionPane.showMessageDialog(this, 
                    "⚠️ Vui lòng chọn khách sạn cần sửa!", 
                    "Thiếu thông tin", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            if (!kiemTraForm()) {
                return;
            }
            
            String tenks = txtTenks.getText().trim();
            String sdt = txtSdt.getText().trim();
            String diachi = txtDiachi.getText().trim();
            
            Hotel hotel = new Hotel(maks, tenks, sdt, diachi);
            
            if (hotelService.updateHotel(maks, hotel)) {
                JOptionPane.showMessageDialog(this, 
                    "✅ Cập nhật khách sạn thành công!", 
                    "Thành công", 
                    JOptionPane.INFORMATION_MESSAGE);
                clearForm();
                loadData();
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "❌ Lỗi: " + e.getMessage(), 
                "Lỗi", 
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
try {
            String maks = txtMaks.getText().trim();
            
            if (maks.isEmpty()) {
                JOptionPane.showMessageDialog(this, 
                    "⚠️ Vui lòng chọn khách sạn cần xóa!", 
                    "Thiếu thông tin", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            int choice = JOptionPane.showConfirmDialog(this, 
                "⚠️ Bạn có chắc muốn xóa khách sạn: " + txtTenks.getText() + "?", 
                "Xác nhận xóa", 
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
            
            if (choice == JOptionPane.YES_OPTION) {
                if (hotelService.deleteHotel(maks)) {
                    JOptionPane.showMessageDialog(this, 
                        "✅ Đã xóa khách sạn thành công!", 
                        "Thành công", 
                        JOptionPane.INFORMATION_MESSAGE);
                    clearForm();
                    loadData();
                }
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "❌ Lỗi: " + e.getMessage(), 
                "Lỗi", 
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try {
            if (!kiemTraForm()) {
                return;
            }
            
            String maks = txtMaks.getText().trim();
            String tenks = txtTenks.getText().trim();
            String sdt = txtSdt.getText().trim();
            String diachi = txtDiachi.getText().trim();
            
            Hotel hotel = new Hotel(maks, tenks, sdt, diachi);
            
            if (hotelService.addHotel(hotel) != null) {
                JOptionPane.showMessageDialog(this, 
                    "✅ Thêm khách sạn thành công!", 
                    "Thành công", 
                    JOptionPane.INFORMATION_MESSAGE);
                clearForm();
                loadData();
            } else {
                JOptionPane.showMessageDialog(this, 
                    "❌ Mã khách sạn đã tồn tại!", 
                    "Lỗi", 
                    JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "❌ Lỗi: " + e.getMessage(), 
                "Lỗi", 
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        try {
            String keyword = txtTimkiem.getText().trim();
            
            if (keyword.isEmpty()) {
                loadData();
                return;
            }
            
            tableModel.setRowCount(0);
            List<Hotel> allHotels = hotelService.getAllHotels();
            int count = 0;
            
            for (Hotel h : allHotels) {
                if (h.getHotelId().toLowerCase().contains(keyword.toLowerCase()) ||
                    h.getHotelName().toLowerCase().contains(keyword.toLowerCase()) ||
                    h.getPhone().contains(keyword) ||
                    h.getAddress().toLowerCase().contains(keyword.toLowerCase())) {
                    
                    Object[] row = {
                        h.getHotelId(),
                        h.getHotelName(),
                        h.getPhone(),
                        h.getAddress()
                    };
                    tableModel.addRow(row);
                    count++;
                }
            }
            
            if (count == 0) {
                JOptionPane.showMessageDialog(this, 
                    "❌ Không tìm thấy khách sạn với từ khóa: " + keyword, 
                    "Kết quả", 
                    JOptionPane.INFORMATION_MESSAGE);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "❌ Lỗi: " + e.getMessage(), 
                "Lỗi", 
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JTextField txtMaks;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtTenks;
    private javax.swing.JTextField txtTimkiem;
    // End of variables declaration//GEN-END:variables
}
