/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import models.Hotel;
import services.HotelService;
import java.util.List;
/**
 *
 * @author xuanb
 */
public class JPanel_qlks extends javax.swing.JPanel {

    /**
     * Creates new form JPanel_qlks
     */    
    private HotelService hotelService;
    private DefaultTableModel tableModel;
    
    public JPanel_qlks() {
                hotelService = new HotelService();
        initComponents();
        setupTableModel();
        loadData();
        setupEventListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        btnTimkiem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        txtMaks = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtTenks = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDiadiem = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtSucchua = new javax.swing.JTextField();
        txtTimkiem = new javax.swing.JTextField();
        btnXoa = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtSdt = new javax.swing.JTextField();

        jLabel4.setText("Sức chứa:");

        btnTimkiem.setText("Tìm kiếm");
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        jLabel1.setText("Mã khách sạn:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã khách sạn", "Tên khách sạn", "Số điện thoại", "Địa điểm", "Sức chứa"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Tên khách sạn:");

        jLabel7.setText("Tìm kiếm");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel3.setText("Địa điểm");

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel5.setText("Số điện thoại:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTimkiem)
                        .addGap(0, 228, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaks)
                            .addComponent(txtTenks)
                            .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDiadiem, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSucchua, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThem)
                            .addComponent(btnXoa)
                            .addComponent(btnSua))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addGap(22, 22, 22)
                        .addComponent(btnXoa))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(txtMaks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtDiadiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSucchua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtTenks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSua)
                    .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimkiem))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    
        private void setupTableModel() {
        tableModel = (DefaultTableModel) jTable1.getModel();
        tableModel.setRowCount(0);
    }
    
    private void setupEventListeners() {
        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int row = jTable1.getSelectedRow();
                if (row >= 0) {
                    txtMaks.setText(jTable1.getValueAt(row, 0).toString());
                    txtTenks.setText(jTable1.getValueAt(row, 1).toString());
                    txtDiadiem.setText(jTable1.getValueAt(row, 2).toString());
                }
            }
        });
    }
    
    private void loadData() {
        tableModel.setRowCount(0);
        try {
            List<Hotel> hotels = hotelService.getAllHotels();
            for (Hotel h : hotels) {
                Object[] row = {
                    h.getHotelId(),
                    h.getHotelName(),
                    h.getLocation()
                };
                tableModel.addRow(row);
            }
            System.out.println("✅ Đã load " + hotels.size() + " khách sạn");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "❌ Lỗi khi load dữ liệu: " + e.getMessage(), 
                "Lỗi", 
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }     
    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        
                try {
            String maks = txtMaks.getText().trim();
            
            if (maks.isEmpty()) {
                JOptionPane.showMessageDialog(this, 
                    "⚠️ Vui lòng chọn khách sạn cần sửa!", 
                    "Thiếu thông tin", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            String tenks = txtTenks.getText().trim();
            String diadiem = txtDiadiem.getText().trim();
            
//            Hotel hotel = new Hotel(maks, tenks, diadiem);
            
//            if (hotelService.updateHotel(maks, hotel)) {
//                JOptionPane.showMessageDialog(this, 
//                    "✅ Cập nhật khách sạn thành công!", 
//                    "Thành công", 
//                    JOptionPane.INFORMATION_MESSAGE);
//                clearForm();
//                loadData();
//            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "❌ Lỗi: " + e.getMessage(), 
                "Lỗi", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
                try {
            String maks = txtMaks.getText().trim();
            
            if (maks.isEmpty()) {
                JOptionPane.showMessageDialog(this, 
                    "⚠️ Vui lòng chọn khách sạn cần xóa!", 
                    "Thiếu thông tin", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            int choice = JOptionPane.showConfirmDialog(this, 
                "⚠️ Bạn có chắc muốn xóa khách sạn: " + maks + "?", 
                "Xác nhận xóa", 
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
            
            if (choice == JOptionPane.YES_OPTION) {
                if (hotelService.deleteHotel(maks)) {
                    JOptionPane.showMessageDialog(this, 
                        "✅ Đã xóa khách sạn thành công!", 
                        "Thành công", 
                        JOptionPane.INFORMATION_MESSAGE);
                    clearForm();
                    loadData();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "❌ Lỗi: " + e.getMessage(), 
                "Lỗi", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        try {
            String maks = txtMaks.getText().trim();
            String tenks = txtTenks.getText().trim();
            String diadiem = txtDiadiem.getText().trim();
            
            if (maks.isEmpty() || tenks.isEmpty() || diadiem.isEmpty()) {
                JOptionPane.showMessageDialog(this, 
                    "⚠️ Vui lòng nhập đầy đủ thông tin!", 
                    "Thiếu thông tin", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }
            
//            Hotel hotel = new Hotel(maks, tenks, diadiem);

            
//            if (hotelService.addHotel(hotel) != null) {
//                JOptionPane.showMessageDialog(this, 
//                    "✅ Thêm khách sạn thành công!", 
//                    "Thành công", 
//                    JOptionPane.INFORMATION_MESSAGE);
//                clearForm();
//                loadData();
//            } else {
//                JOptionPane.showMessageDialog(this, 
//                    "❌ Mã khách sạn đã tồn tại!", 
//                    "Lỗi", 
//                    JOptionPane.ERROR_MESSAGE);
//            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "❌ Lỗi: " + e.getMessage(), 
                "Lỗi", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed
        // TODO add your handling code here:
        
        try {
            String keyword = txtTimkiem.getText().trim();
            
            if (keyword.isEmpty()) {
                loadData();
                return;
            }
            
            tableModel.setRowCount(0);
            List<Hotel> allHotels = hotelService.getAllHotels();
            int count = 0;
            
            for (Hotel h : allHotels) {
                if (h.getHotelId().toLowerCase().contains(keyword.toLowerCase()) ||
                    h.getHotelName().toLowerCase().contains(keyword.toLowerCase()) ||
                    h.getLocation().toLowerCase().contains(keyword.toLowerCase())) {
                    
                    Object[] row = {
                        h.getHotelId(),
                        h.getHotelName(),
                        h.getLocation()
                    };
                    tableModel.addRow(row);
                    count++;
                }
            }
            
            if (count == 0) {
                JOptionPane.showMessageDialog(this, 
                    "❌ Không tìm thấy khách sạn!", 
                    "Kết quả", 
                    JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "❌ Lỗi: " + e.getMessage(), 
                "Lỗi", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTimkiemActionPerformed
                                      
    
    private void clearForm() {
        txtMaks.setText("");
        txtTenks.setText("");
        txtDiadiem.setText("");
        txtTimkiem.setText("");
        jTable1.clearSelection();
        txtMaks.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDiadiem;
    private javax.swing.JTextField txtMaks;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtSucchua;
    private javax.swing.JTextField txtTenks;
    private javax.swing.JTextField txtTimkiem;
    // End of variables declaration//GEN-END:variables
}
