/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.*;
import models.Customer;
import services.CustomerService;
import java.util.List;
import java.util.Date;
import java.text.SimpleDateFormat;

/**
 *
 * @author xuanb
 */
public class JPanel_qltaikhoan extends javax.swing.JPanel {

    private CustomerService customerService;
    private DefaultTableModel tableModel;
    private SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");

    /**
     * Creates new form JPanel_qltaikhoan
     */
    public JPanel_qltaikhoan() {
        customerService = new CustomerService();
        initComponents();
        setupTableModel();
        setupEventListeners();
        loadData();
        this.addComponentListener(new java.awt.event.ComponentAdapter() {
        @Override
        public void componentShown(java.awt.event.ComponentEvent evt) {
            System.out.println("🔄 [Quản lý TK] Panel hiển thị, đang reload...");
            loadData();
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomers = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTimkiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHoten = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSdt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        cboAccountType = new javax.swing.JComboBox<>();
        cboGioitinh = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnResetPass = new javax.swing.JButton();

        tblCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã khách hàng", "UserName", "Họ Tên", "Số điện thoại", "Email", "Loại tài khoản", "Giới tính"
            }
        ));
        jScrollPane1.setViewportView(tblCustomers);

        jLabel1.setText("Tìm kiếm");

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã khách hàng");

        jLabel3.setText("UserName");

        jLabel4.setText("Mật khẩu");

        jLabel5.setText("Họ tên");

        jLabel6.setText("Số điện thoại");

        jLabel7.setText("Email");

        cboAccountType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CUSTOMER", "ADMIN" }));

        cboGioitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE" }));

        jLabel8.setText("Loại tài khoản");

        jLabel9.setText("Giới tính");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnResetPass.setText("Reset mật khẩu");
        btnResetPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboAccountType, 0, 110, Short.MAX_VALUE)
                                    .addComponent(txtPassword))))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtHoten, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboGioitinh, 0, 110, Short.MAX_VALUE)
                                    .addComponent(txtEmail)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTimKiem)
                        .addGap(58, 58, 58)))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSua)
                    .addComponent(btnThem)
                    .addComponent(btnXoa))
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnResetPass)
                .addGap(9, 9, 9))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtHoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnSua)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboGioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnXoa)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btnResetPass)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        try {
            if (!kiemTraForm(true)) {
                return;
            }

            String maKH = txtMaKH.getText().trim();
            String username = txtUsername.getText().trim();
            String password = new String(txtPassword.getPassword()).trim();
            String hoten = txtHoten.getText().trim();
            String sdt = txtSdt.getText().trim();
            String email = txtEmail.getText().trim();
            String accountType = cboAccountType.getSelectedItem().toString();
            String gioitinh = cboGioitinh.getSelectedItem().toString();

            Customer customer = new Customer();
            customer.setCustomerId(maKH);
            customer.setUsername(username.isEmpty() ? null : username);
            customer.setPassword(password.isEmpty() ? null : password);
            customer.setFullName(hoten);
            customer.setPhone(sdt);
            customer.setEmail(email.isEmpty() ? null : email);
            customer.setAccountType(accountType);
            customer.setGender(gioitinh);
            customer.setCreatedAt(new Date());

            if (customerService.addCustomer(customer) != null) {
                JOptionPane.showMessageDialog(this,
                        "✅ Thêm tài khoản thành công!",
                        "Thành công",
                        JOptionPane.INFORMATION_MESSAGE);
                clearForm();
                loadData();
            } else {
                JOptionPane.showMessageDialog(this,
                        "❌ Mã khách hàng hoặc username đã tồn tại!",
                        "Lỗi",
                        JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "❌ Lỗi: " + e.getMessage(),
                    "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        try {
            String maKH = txtMaKH.getText().trim();

            if (maKH.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "⚠️ Vui lòng chọn tài khoản cần sửa!",
                        "Thiếu thông tin",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            if (!kiemTraForm(false)) {
                return;
            }

            Customer customer = customerService.findCustomerById(maKH);
            if (customer == null) {
                JOptionPane.showMessageDialog(this,
                        "❌ Không tìm thấy tài khoản!",
                        "Lỗi",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Update thông tin
            String username = txtUsername.getText().trim();
            String password = new String(txtPassword.getPassword()).trim();

            customer.setUsername(username.isEmpty() ? null : username);

            // Chỉ đổi password nếu nhập mới
            if (!password.isEmpty()) {
                customer.setPassword(password);
            }

            customer.setFullName(txtHoten.getText().trim());
            customer.setPhone(txtSdt.getText().trim());
            customer.setEmail(txtEmail.getText().trim());
            customer.setAccountType(cboAccountType.getSelectedItem().toString());
            customer.setGender(cboGioitinh.getSelectedItem().toString());

            if (customerService.updateCustomer(maKH, customer)) {
                JOptionPane.showMessageDialog(this,
                        "✅ Cập nhật tài khoản thành công!",
                        "Thành công",
                        JOptionPane.INFORMATION_MESSAGE);
                clearForm();
                loadData();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "❌ Lỗi: " + e.getMessage(),
                    "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        try {
            String maKH = txtMaKH.getText().trim();

            if (maKH.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "⚠️ Vui lòng chọn tài khoản cần xóa!",
                        "Thiếu thông tin",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            int choice = JOptionPane.showConfirmDialog(this,
                    "⚠️ Bạn có chắc muốn xóa tài khoản: " + txtHoten.getText() + "?\n"
                    + "Hành động này không thể hoàn tác!",
                    "Xác nhận xóa",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);

            if (choice == JOptionPane.YES_OPTION) {
                if (customerService.deleteCustomer(maKH)) {
                    JOptionPane.showMessageDialog(this,
                            "✅ Đã xóa tài khoản thành công!",
                            "Thành công",
                            JOptionPane.INFORMATION_MESSAGE);
                    clearForm();
                    loadData();
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "❌ Lỗi: " + e.getMessage(),
                    "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        try {
            String keyword = txtTimkiem.getText().trim();

            if (keyword.isEmpty()) {
                loadData();
                return;
            }

            tableModel.setRowCount(0);
            List<Customer> allCustomers = customerService.getAllCustomers();
            int count = 0;

            for (Customer c : allCustomers) {
                if (c.getCustomerId().toLowerCase().contains(keyword.toLowerCase())
                        || (c.getUsername() != null && c.getUsername().toLowerCase().contains(keyword.toLowerCase()))
                        || c.getFullName().toLowerCase().contains(keyword.toLowerCase())
                        || c.getPhone().contains(keyword)
                        || (c.getEmail() != null && c.getEmail().toLowerCase().contains(keyword.toLowerCase()))
                        || c.getAccountType().toLowerCase().contains(keyword.toLowerCase())) {

                    Object[] row = {
                        c.getCustomerId(),
                        c.getUsername() != null ? c.getUsername() : "(Chưa có)",
                        c.getFullName(),
                        c.getPhone(),
                        c.getEmail(),
                        c.getAccountType(),
                        c.getGender()
                    };
                    tableModel.addRow(row);
                    count++;
                }
            }

            if (count == 0) {
                JOptionPane.showMessageDialog(this,
                        "❌ Không tìm thấy tài khoản với từ khóa: " + keyword,
                        "Kết quả",
                        JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "❌ Lỗi: " + e.getMessage(),
                    "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnResetPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetPassActionPerformed
        // TODO add your handling code here:
        try {
            String maKH = txtMaKH.getText().trim();

            if (maKH.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "⚠️ Vui lòng chọn tài khoản cần reset mật khẩu!",
                        "Thiếu thông tin",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            int choice = JOptionPane.showConfirmDialog(this,
                    "⚠️ Reset mật khẩu về: 123456?\n"
                    + "Tài khoản: " + txtUsername.getText(),
                    "Xác nhận reset",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            if (choice == JOptionPane.YES_OPTION) {
                Customer customer = customerService.findCustomerById(maKH);
                if (customer != null) {
                    customer.setPassword("123456");

                    if (customerService.updateCustomer(maKH, customer)) {
                        JOptionPane.showMessageDialog(this,
                                "✅ Đã reset mật khẩu thành công!\nMật khẩu mới: 123456",
                                "Thành công",
                                JOptionPane.INFORMATION_MESSAGE);
                        clearForm();
                    }
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "❌ Lỗi: " + e.getMessage(),
                    "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnResetPassActionPerformed

    private void setupTableModel() {
        tableModel = (DefaultTableModel) tblCustomers.getModel();
        tableModel.setRowCount(0);
    }

    private void setupEventListeners() {
        tblCustomers.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                dienFormTuBang();
            }
        });

        txtTimkiem.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    btnTimKiemActionPerformed(null);
                }
            }
        });

        // Disable username khi sửa
        txtMaKH.setEnabled(true);

        // Tooltip
        txtPassword.setToolTipText("Để trống nếu không muốn đổi mật khẩu khi sửa");
    }

    private void loadData() {
        tableModel.setRowCount(0);
        try {
            List<Customer> customers = customerService.getAllCustomers();

            for (Customer c : customers) {
                Object[] row = {
                    c.getCustomerId(),
                    c.getUsername() != null ? c.getUsername() : "(Chưa có)",
                    c.getFullName(),
                    c.getPhone(),
                    c.getEmail(),
                    c.getAccountType(),
                    c.getGender()
                };
                tableModel.addRow(row);
            }

            System.out.println("✅ Đã load " + customers.size() + " customers");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "❌ Lỗi khi load dữ liệu: " + e.getMessage(),
                    "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    private void dienFormTuBang() {
        int row = tblCustomers.getSelectedRow();
        if (row >= 0) {
            try {
                String maKH = tblCustomers.getValueAt(row, 0).toString();
                Customer customer = customerService.findCustomerById(maKH);

                if (customer != null) {
                    txtMaKH.setText(customer.getCustomerId());
                    txtUsername.setText(customer.getUsername() != null ? customer.getUsername() : "");
                    txtPassword.setText(""); // Không hiện password
                    txtHoten.setText(customer.getFullName());
                    txtSdt.setText(customer.getPhone());
                    txtEmail.setText(customer.getEmail() != null ? customer.getEmail() : "");

                    cboAccountType.setSelectedItem(customer.getAccountType());
                    cboGioitinh.setSelectedItem(customer.getGender());

                    txtMaKH.setEnabled(false); // Không cho sửa mã
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    private void btnLammoiActionPerformed(java.awt.event.ActionEvent evt) {
        clearForm();
        loadData();
    }



    private boolean kiemTraForm(boolean isAdd) {
        if (txtMaKH.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "⚠️ Vui lòng nhập mã khách hàng!");
            txtMaKH.requestFocus();
            return false;
        }

        if (txtHoten.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "⚠️ Vui lòng nhập họ tên!");
            txtHoten.requestFocus();
            return false;
        }

        if (txtSdt.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "⚠️ Vui lòng nhập số điện thoại!");
            txtSdt.requestFocus();
            return false;
        }

        // Chỉ check username/password khi thêm mới HOẶC accountType != GUEST
        String accountType = cboAccountType.getSelectedItem().toString();
        if (isAdd && !"GUEST".equals(accountType)) {
            if (txtUsername.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "⚠️ Vui lòng nhập username!");
                txtUsername.requestFocus();
                return false;
            }

            if (new String(txtPassword.getPassword()).trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "⚠️ Vui lòng nhập password!");
                txtPassword.requestFocus();
                return false;
            }
        }

        return true;
    }

    private void clearForm() {
        txtMaKH.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
        txtHoten.setText("");
        txtSdt.setText("");
        txtEmail.setText("");
        txtTimkiem.setText("");
        cboAccountType.setSelectedIndex(0); // CUSTOMER
        cboGioitinh.setSelectedIndex(0); // MALE
        tblCustomers.clearSelection();
        txtMaKH.setEnabled(true);
        txtMaKH.requestFocus();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResetPass;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboAccountType;
    private javax.swing.JComboBox<String> cboGioitinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCustomers;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtTimkiem;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
